version: '3'

services:
  #postgres:
  #  image: postgres
  #  restart: on-failure  
  #  ports:
  #    - "5432:5432"
  #  container_name: db

  backend:
    build: ./src/backend
    restart: on-failure
    volumes:
      - ./src/backend/nest:/home/node/app  
    ports:
      - "3000:3000"
    container_name: backend
    working_dir: /home/node/app
    user: root