version: '3'

services:

  backend:
    build: ./src/backend
    restart: on-failure
    volumes:
      - ./src/backend/nest:/home/node/app
    ports:
      - "3000:3000"
    container_name: backend
    user: root
    env_file:
      - ./src/backend/nest/.env
    environment:
      - DATABASE_URL
    networks:
      - transcendence
    depends_on:
      - database

  frontend:
    build: ./src/frontend
    restart: on-failure
    volumes:
    - ./src/frontend/react:/home/node/app
    ports:
      - "5173:5173"
    container_name: frontend
    # depends_on:
    #   - backend
    user: root
    networks:
      - transcendence

  database:
    image: postgres:latest
    container_name: database
    restart: on-failure
    networks:
      - db
    env_file:
      - .env
      - ./src/backend/nest/.env
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"

networks:
  transcendence:
    driver: bridge
  db:
    driver: bridge