version: "3"

services:
  backend:
    build: ./src/backend
    restart: on-failure
    volumes:
      - ./src/backend/nest:/home/node/app
    ports:
      - 3000:3000
      - 5555:5555 # open port for prisma studio
    container_name: backend
    user: root
    env_file:
      - ./src/backend/nest/.env
    networks:
      - transcendence
    depends_on:
      - database

  frontend:
    build: ./src/frontend
    restart: on-failure
    volumes:
      - ./src/frontend/react:/home/node/app
    ports:
      - 5173:5173
    container_name: frontend
    depends_on:
      - backend
    user: root
    networks:
      - transcendence

  database:
    image: postgres:latest
    container_name: database
    restart: always
    networks:
      - transcendence
    env_file:
      - ./src/backend/nest/.env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  transcendence:
    name: transcendence
    driver: bridge

volumes:
  postgres:
    name: nest-db
