version: '3'

services:

  backend:
    build: ./src/backend
    restart: on-failure
    volumes:
      - ./src/backend/nest:/home/node/app  
    ports:
      - "3000:3000"
    container_name: backend
    user: root