version: '3'

services:
  #postgres:
  #  image: postgres
  #  restart: on-failure  
  #  ports:
  #    - "5432:5432"
  #  container_name: db

  backend:
    build: ./src/backend
    restart: on-failure
    volumes:
      - ./src/backend:/home/node/app  
    ports:
      - "3000:3000"
    container_name: backend
    working_dir: /home/node/app
    user: root

  frontend:
    image: node
    restart: on-failure
    volumes:
      - ./src/frontend:/home/node/app
    ports:
      - '5173:5173'
    container_name: frontend
    depends_on:
      - backend
    user: node
    working_dir: /home/node/app
    entrypoint: ["bash" , "-c" , "tail -f /dev/null"]

networks:
  transcendence:
    driver: bridge

volumes:
  v_db:
    driver_opts:
      type: none
      o: bind
      device: ${DB_VOL_LOC}